import axios from 'axios';
import Head from 'next/head';
import { useEffect } from 'react';

import { useStore } from '../src/zustand/store';

export default function Home() {
  const user = useStore((state) => state.user);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {user ? <h2>{user.email}</h2> : <h2>no user</h2>}
    </div>
  );
}
